repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    # renovate: datasource=github-tags depName=pre-commit/pre-commit-hooks
    rev: cef0300fd0fc4d2a87a85fa2093c6b283ea36f4b # v5.0.0 # pragma: allowlist secret
    hooks:
      - id: trailing-whitespace
        args: ["--markdown-linebreak-ext=md"]
      - id: check-merge-conflict
      - id: detect-aws-credentials
        args: ["--allow-missing-credentials"]
      - id: detect-private-key
      - id: end-of-file-fixer

  - repo: https://github.com/norwoodj/helm-docs
    rev: 37d3055fece566105cf8cff7c17b7b2355a01677 # v1.14.2 # pragma: allowlist secret
    hooks:
      - id: helm-docs
        args:
          # Make the tool search for charts only under the `charts` directory
          - --chart-search-root=charts
