{{- if .Values.config.create }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kube-scheduler.configMapName" . }}
  labels:
    {{- include "kube-scheduler.labels" . | nindent 4 }}
data:
  scheduler-config.yaml: {{ .Values.config.kubeSchedulerConfig | quote}}
{{- end }}
